baseURL = "https://cuteloop.github.io/InfiniteCuteLoop/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"
publishDir = "docs"



[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[menu]
  [[menu.main]]
  name = "Home"
  url = ""
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Categories"
  url = "categories/"
  weight = 3

  [[menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 4

  [[menu.main]]
  name = "Subscribe"
  url = "index.xml"
  weight = 5

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy;  2024 -- {Year} | [Github](https://github.com/CuteLoop) |"

[markup]
  [markup.highlight]
    codeFences = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [ ["\\[", "\\]"], ["$$", "$$"] ]
          inline = [ ["\\(", "\\)"] ]
